
# Project information
site_url: https://github.com/tgaspar/linux-fe/
site_author: Timotej Gašpar
site_description: >-
  Linux for roboticists.
# Repository
repo_name: tgaspar/
repo_url: https://github.com/tgaspar/linux-fe

site_name: Robolab Linux
nav:
    - Home: 'index.md'
    # - About: 'about/index.md'
    - The Workshop:
      - Introduction: 'workshop/introduction.md'
      - The command line: 'workshop/command-line.md'
      - Filesystem and navigation: 'workshop/filesystem-and-navigation.md'
      - Users, groups and permissions: 'workshop/usr-grp-perm.md'
      - Pipes, redirects and File editing: 'workshop/piping-text-editing.md'
      - Process management: 'workshop/process-management.md'
      - Remote access: 'workshop/remote-access.md'
      - Installing new tools : 'workshop/git-and-apt.md'
      - Shell scripts: 'workshop/shell-scripting.md'
    - Final Assignment: 'practical/index.md'
    - Additional knowledge: 'additional/index.md'
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
      - toc.integrate
  favicon: assets/logo.png
  # logo: https://raw.githubusercontent.com/ros-infrastructure/artwork/master/orgunits/ros.svg

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - with-pdf:
        # author: Timotej Gašpar
        copyright: 'Copyright: Laboratory of robotics, Faculty of Electrical Engineering'
        #
        #cover: false
        #back_cover: true
        cover_logo: 'Cover Logo'
        #cover_title: TITLE TEXT
        cover_subtitle: A practical workshop for students who want to learn Linux
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        #two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        #output_path: any-place/document.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        # debug_html: true
        #show_anchors: true
        # verbose: true