
# Project information
site_url: https://ros-fe.github.io/fe-ros-docs/
site_author: Timotej Gašpar
site_description: >-
  FE ROS workshop documentation page.
# Repository
repo_name: tgaspar/
repo_url: https://github.com/tgaspar/linux-fe

site_name: FE ROS
nav:
    - Home: 'index.md'
    - About: 'about/index.md'
    - The Workshop:
      - Introduction: 'workshop/introduction.md'
      - The command line: 'workshop/command-line.md'
      - Filesystem and navigation: 'workshop/filesystem-and-navigation.md'
      - Users, groups and permissions: 'workshop/usr-grp-perm.md'
      - Pipes, Redirects and scripts: 'workshop/shell-scripting.md'
      - Process management: 'workshop/process-management.md'
      - Remote access: 'workshop/remote-access.md'
      - Text editing : 'workshop/git-and-apt'
    - Final Assignment: 'practical/index.md'
    - Additional knowledge: 'additional/index.md'
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
      - toc.integrate
  favicon: assets/logo.png
  # logo: https://raw.githubusercontent.com/ros-infrastructure/artwork/master/orgunits/ros.svg

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
